using System.Globalization;
using System.Text;
using UnrealKit.Core.Diagnostics;

namespace UnrealKit.Core.Parsing;

public sealed class StaticCameraHtmlReportService : IStaticCameraHtmlReportService
{
    public async Task<StaticCameraHtmlReportResult> GenerateAsync(
        StaticCameraHtmlReportRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.OutputFilePath);
        ArgumentNullException.ThrowIfNull(request.ParseResult);

        var config = request.Config ?? StaticCameraPerfConfig.Default;
        config.Validate();

        var outputPath = Path.GetFullPath(request.OutputFilePath);
        var outputDir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrWhiteSpace(outputDir))
            Directory.CreateDirectory(outputDir);

        var html = BuildHtml(request.ParseResult, config, outputDir!);
        await File.WriteAllTextAsync(outputPath, html, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false), cancellationToken);

        return new StaticCameraHtmlReportResult(outputPath);
    }

    private static string BuildHtml(StaticCameraPerfParseResult result, StaticCameraPerfConfig config, string outputDir)
    {
        var sb = new StringBuilder();
        var report = result.Report;

        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"zh-CN\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"UTF-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        sb.AppendLine("<title>Static Camera Performance Report</title>");
        AppendStyles(sb);
        AppendScript(sb);
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");
        sb.AppendLine("<div class=\"container\">");

        sb.AppendLine("<header>");
        sb.AppendLine("<h1>&#x1F4F7; Static Camera Performance Report</h1>");
        sb.AppendFormat("<p class=\"subtitle\">Source: {0}</p>", EscapeHtml(result.InputPath));
        sb.AppendLine();
        sb.AppendLine("</header>");

        if (report is not null)
        {
            AppendDeviceInfo(sb, report.DeviceInfo);
            AppendSummary(sb, report, config, result.Diagnostics);
            AppendCameraDetails(sb, report, config, outputDir);
        }

        AppendDiagnostics(sb, result.Diagnostics);

        sb.AppendLine("<div class=\"footer\">Generated by UnrealKit</div>");
        sb.AppendLine("</div>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return sb.ToString();
    }

    private static void AppendScript(StringBuilder sb)
    {
        sb.AppendLine("<script>");
        sb.AppendLine("function toggleCollapsible(id) {");
        sb.AppendLine("  var el = document.getElementById(id);");
        sb.AppendLine("  if (!el) return;");
        sb.AppendLine("  el.classList.toggle('collapsed');");
        sb.AppendLine("  var toggle = el.previousElementSibling;");
        sb.AppendLine("  if (toggle) toggle.classList.toggle('open');");
        sb.AppendLine("}");
        sb.AppendLine("</script>");
    }

    private static void AppendStyles(StringBuilder sb)
    {
        sb.AppendLine("<style>");
        sb.AppendLine(@"
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f7fa; color: #1b263b; line-height: 1.6; }
    .container { max-width: 1200px; margin: 0 auto; padding: 24px; }
    header { background: linear-gradient(135deg, #1b263b, #415a77); color: white; padding: 32px; border-radius: 8px; margin-bottom: 24px; }
    header h1 { font-size: 28px; font-weight: 600; }
    header .subtitle { font-size: 14px; opacity: 0.8; margin-top: 8px; word-break: break-all; }
    h2 { font-size: 20px; font-weight: 600; color: #1b263b; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 2px solid #e2e6ea; }
    .card { background: white; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); padding: 24px; margin-bottom: 24px; }
    .info-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 12px; }
    .info-item { display: flex; flex-direction: column; }
    .info-label { font-size: 12px; color: #778da9; text-transform: uppercase; letter-spacing: 0.5px; }
    .info-value { font-size: 14px; font-weight: 500; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th { background: #e2e6ea; font-weight: 600; text-align: left; padding: 10px 12px; border-bottom: 2px solid #cbd5e1; }
    td { padding: 8px 12px; border-bottom: 1px solid #f0f3f7; }
    tr:hover td { background: #f8fafd; }
    .threshold-ok { color: #16a34a; }
    .threshold-warn { color: #d97706; font-weight: 600; }
    .threshold-error { color: #dc2626; font-weight: 700; }
    .camera-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }
    .camera-name { font-size: 18px; font-weight: 600; }
    .camera-badge { font-size: 12px; padding: 2px 8px; border-radius: 4px; font-weight: 500; }
    .badge-ok { background: #dcfce7; color: #16a34a; }
    .badge-warn { background: #fef3c7; color: #d97706; }
    .badge-error { background: #fee2e2; color: #dc2626; }
    .screenshots { display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); gap: 8px; margin-top: 12px; }
    .screenshot-card { border: 1px solid #e2e6ea; border-radius: 4px; overflow: hidden; background: #f8fafd; }
    .screenshot-card img { width: 100%; height: auto; display: block; }
    .screenshot-card .caption { font-size: 11px; padding: 4px 8px; color: #64748b; word-break: break-all; }
    .diag-list { list-style: none; }
    .diag-item { display: flex; gap: 12px; padding: 8px 12px; border-radius: 4px; margin-bottom: 4px; font-size: 13px; }
    .diag-error { background: #fee2e2; }
    .diag-warn { background: #fef3c7; }
    .diag-code { font-family: 'Consolas', monospace; font-weight: 600; min-width: 72px; }
    .diag-msg { flex: 1; }
    .diag-location { color: #64748b; font-size: 12px; white-space: nowrap; }
    .footer { text-align: center; color: #94a3b8; font-size: 12px; margin-top: 32px; padding: 16px; }
    .collapsible-toggle { cursor: pointer; user-select: none; display: flex; align-items: center; gap: 8px; }
    .collapsible-toggle::before { content: '\25B6'; display: inline-block; transition: transform 0.2s; font-size: 12px; width: 16px; }
    .collapsible-toggle.open::before { transform: rotate(90deg); }
    .collapsible-content { overflow: hidden; }
    .collapsible-content.collapsed { display: none; }
    @media (max-width: 768px) {
        .container { padding: 12px; }
        header { padding: 20px; }
        .card { padding: 16px; }
        .info-grid { grid-template-columns: 1fr; }
        .screenshots { grid-template-columns: repeat(auto-fill, minmax(100px, 1fr)); }
    }
");
        sb.AppendLine("</style>");
    }

    private static void AppendDeviceInfo(StringBuilder sb, StaticCameraPerfDeviceInfo info)
    {
        sb.AppendLine("<div class=\"card\">");
        sb.AppendLine("<h2>Device Information</h2>");
        sb.AppendLine("<div class=\"info-grid\">");

        AppendInfoField(sb, "OS Platform", info.OsPlatform);
        AppendInfoField(sb, "Device Make", info.DeviceMake);
        AppendInfoField(sb, "GPU Vendor", info.GpuVendor);
        AppendInfoField(sb, "Vulkan Available", info.VulkanAvailable?.ToString());
        AppendInfoField(sb, "Vulkan Version", info.VulkanVersion);

        sb.AppendLine("</div>");
        sb.AppendLine("</div>");
    }

    private static void AppendInfoField(StringBuilder sb, string label, string? value)
    {
        if (value is null) return;
        sb.AppendLine("<div class=\"info-item\">");
        sb.AppendFormat("<span class=\"info-label\">{0}</span>", EscapeHtml(label));
        sb.AppendLine();
        sb.AppendFormat("<span class=\"info-value\">{0}</span>", EscapeHtml(value));
        sb.AppendLine();
        sb.AppendLine("</div>");
    }

    private static void AppendSummary(StringBuilder sb, StaticCameraPerfReport report, StaticCameraPerfConfig config, IReadOnlyList<Diagnostic> diagnostics)
    {
        sb.AppendLine("<div class=\"card\">");
        sb.AppendLine("<h2>Summary</h2>");

        sb.AppendLine("<div class=\"info-grid\" style=\"margin-bottom:20px\">");
        AppendInfoField(sb, "Camera Count", report.CameraCount.ToString());
        AppendInfoField(sb, "Parsed Cameras", report.ParseCameraCount.ToString());
        AppendInfoField(sb, "Completeness", report.Completeness.ToString());
        AppendInfoField(sb, "Diagnostics", diagnostics.Count.ToString());
        sb.AppendLine("</div>");

        sb.AppendLine("<table>");
        sb.AppendLine("<thead><tr>");
        sb.AppendLine("<th>Metric</th><th>Average</th><th>Warning</th><th>Error</th><th>Status</th>");
        sb.AppendLine("</tr></thead><tbody>");

        AppendMetricRow(sb, "Frame Time", report.Average.FrameTimeMs, "ms", config.FrameTimeWarningMs, config.FrameTimeErrorMs, higherIsWorse: true);
        AppendMetricRow(sb, "Game Time", report.Average.GameTimeMs, "ms", null, null, null);
        AppendMetricRow(sb, "Draw Time", report.Average.DrawTimeMs, "ms", null, null, null);
        AppendMetricRow(sb, "RHI Time", report.Average.RhiTimeMs, "ms", null, null, null);
        AppendMetricRow(sb, "GPU Time", report.Average.GpuTimeMs, "ms", null, null, null);
        AppendMetricRow(sb, "Memory", report.Average.MemoryBytes, "bytes", null, null, null);
        AppendMetricRow(sb, "Draw Calls", report.Average.DrawCalls, "", config.DrawCallWarning, config.DrawCallError, higherIsWorse: true);
        AppendMetricRow(sb, "Triangles", report.Average.Triangles, "", config.TriangleWarning, config.TriangleError, higherIsWorse: true);

        sb.AppendLine("</tbody></table>");
        sb.AppendLine("</div>");
    }

    private static void AppendMetricRow(StringBuilder sb, string name, double value, string unit, double? warningThreshold, double? errorThreshold, bool? higherIsWorse)
    {
        var (status, cssClass) = GetThresholdStatus(value, warningThreshold, errorThreshold, higherIsWorse ?? false);
        sb.AppendLine("<tr>");
        sb.AppendFormat("<td>{0}</td>", EscapeHtml(name));
        sb.AppendLine();
        sb.AppendFormat("<td class=\"{0}\">{1} {2}</td>", cssClass, value.ToString("F2", CultureInfo.InvariantCulture), EscapeHtml(unit));
        sb.AppendLine();
        sb.AppendFormat("<td>{0}</td>", warningThreshold?.ToString(CultureInfo.InvariantCulture) ?? "-");
        sb.AppendLine();
        sb.AppendFormat("<td>{0}</td>", errorThreshold?.ToString(CultureInfo.InvariantCulture) ?? "-");
        sb.AppendLine();
        sb.AppendFormat("<td class=\"{0}\">{1}</td>", cssClass, status);
        sb.AppendLine();
        sb.AppendLine("</tr>");
    }

    private static void AppendMetricRow(StringBuilder sb, string name, long value, string unit, long? warningThreshold, long? errorThreshold, bool? higherIsWorse)
    {
        var (status, cssClass) = GetThresholdStatus(value, warningThreshold, errorThreshold, higherIsWorse ?? false);
        sb.AppendLine("<tr>");
        sb.AppendFormat("<td>{0}</td>", EscapeHtml(name));
        sb.AppendLine();
        sb.AppendFormat("<td class=\"{0}\">{1} {2}</td>", cssClass, value.ToString(CultureInfo.InvariantCulture), EscapeHtml(unit));
        sb.AppendLine();
        sb.AppendFormat("<td>{0}</td>", warningThreshold?.ToString(CultureInfo.InvariantCulture) ?? "-");
        sb.AppendLine();
        sb.AppendFormat("<td>{0}</td>", errorThreshold?.ToString(CultureInfo.InvariantCulture) ?? "-");
        sb.AppendLine();
        sb.AppendFormat("<td class=\"{0}\">{1}</td>", cssClass, status);
        sb.AppendLine();
        sb.AppendLine("</tr>");
    }

    private static (string Status, string CssClass) GetThresholdStatus(double value, double? warning, double? error, bool higherIsWorse)
    {
        if (error.HasValue && (higherIsWorse ? value >= error.Value : value <= error.Value))
            return ("ERROR", "threshold-error");
        if (warning.HasValue && (higherIsWorse ? value >= warning.Value : value <= warning.Value))
            return ("WARNING", "threshold-warn");
        return ("OK", "threshold-ok");
    }

    private static (string Status, string CssClass) GetThresholdStatus(long value, long? warning, long? error, bool higherIsWorse)
    {
        if (error.HasValue && (higherIsWorse ? value >= error.Value : value <= error.Value))
            return ("ERROR", "threshold-error");
        if (warning.HasValue && (higherIsWorse ? value >= warning.Value : value <= warning.Value))
            return ("WARNING", "threshold-warn");
        return ("OK", "threshold-ok");
    }

    private static void AppendCameraDetails(StringBuilder sb, StaticCameraPerfReport report, StaticCameraPerfConfig config, string outputDir)
    {
        sb.AppendLine("<div class=\"card\">");
        sb.AppendLine("<h2>Camera Details</h2>");

        for (var i = 0; i < report.Frames.Count; i++)
        {
            AppendCameraCard(sb, report.Frames[i], config, outputDir, i);
        }

        sb.AppendLine("</div>");
    }

    private static void AppendCameraCard(StringBuilder sb, StaticCameraPerfFrame frame, StaticCameraPerfConfig config, string outputDir, int index)
    {
        var ftStatus = GetThresholdStatus(frame.FrameTimeMs, config.FrameTimeWarningMs, config.FrameTimeErrorMs, higherIsWorse: true);
        var dcStatus = GetThresholdStatus(frame.DrawCalls, config.DrawCallWarning, config.DrawCallError, higherIsWorse: true);
        var primStatus = GetThresholdStatus(frame.Triangles, config.TriangleWarning, config.TriangleError, higherIsWorse: true);

        var worstStatus = "OK";
        var worstCss = "badge-ok";
        if (ftStatus.Status == "ERROR" || dcStatus.Status == "ERROR" || primStatus.Status == "ERROR")
        { worstStatus = "ERROR"; worstCss = "badge-error"; }
        else if (ftStatus.Status == "WARNING" || dcStatus.Status == "WARNING" || primStatus.Status == "WARNING")
        { worstStatus = "WARNING"; worstCss = "badge-warn"; }

        var cameraId = $"camera-{index}";

        sb.AppendLine("<div style=\"border:1px solid #e2e6ea; border-radius:6px; padding:16px; margin-bottom:16px\">");
        sb.AppendFormat("<div class=\"camera-header\">");
        sb.AppendLine();
        sb.AppendFormat("<span class=\"collapsible-toggle open\" onclick=\"toggleCollapsible('{0}')\">", cameraId);
        sb.AppendFormat("<span class=\"camera-name\">{0} (#{1})</span>", EscapeHtml(frame.CameraName), frame.Index);
        sb.AppendLine("</span>");
        sb.AppendFormat("<span class=\"camera-badge {0}\">{1}</span>", worstCss, worstStatus);
        sb.AppendLine("</div>");

        sb.AppendFormat("<div id=\"{0}\" class=\"collapsible-content\">", cameraId);
        sb.AppendLine();

        sb.AppendLine("<table>");
        sb.AppendLine("<thead><tr><th>Metric</th><th>Value</th><th>Threshold</th><th>Status</th></tr></thead><tbody>");

        AppendFrameMetricRow(sb, "Frame Time", frame.FrameTimeMs, "ms", config.FrameTimeWarningMs, config.FrameTimeErrorMs, higherIsWorse: true);
        AppendFrameMetricRow(sb, "Game Time", frame.GameTimeMs, "ms", null, null, null);
        AppendFrameMetricRow(sb, "Draw Time", frame.DrawTimeMs, "ms", null, null, null);
        AppendFrameMetricRow(sb, "RHI Time", frame.RhiTimeMs, "ms", null, null, null);
        AppendFrameMetricRow(sb, "GPU Time", frame.GpuTimeMs, "ms", null, null, null);
        AppendFrameMetricRow(sb, "Memory", frame.MemoryBytes, "bytes", null, null, null);
        AppendFrameMetricRow(sb, "Draw Calls", frame.DrawCalls, "", config.DrawCallWarning, config.DrawCallError, higherIsWorse: true);
        AppendFrameMetricRow(sb, "Triangles", frame.Triangles, "", config.TriangleWarning, config.TriangleError, higherIsWorse: true);

        sb.AppendLine("</tbody></table>");

        if (frame.Screenshots.Count > 0)
        {
            sb.AppendFormat("<p style=\"margin-top:12px;font-weight:600;font-size:14px\">Screenshots ({0})</p>", frame.Screenshots.Count);
            sb.AppendLine();
            sb.AppendLine("<div class=\"screenshots\">");
            foreach (var screenshot in frame.Screenshots)
            {
                var relativePath = GetRelativePath(outputDir, screenshot);
                sb.AppendLine("<div class=\"screenshot-card\">");
                sb.AppendFormat("<img src=\"{0}\" alt=\"{1}\" loading=\"lazy\" />", EscapeHtml(relativePath), EscapeHtml(Path.GetFileName(screenshot)));
                sb.AppendLine();
                sb.AppendFormat("<div class=\"caption\">{0}</div>", EscapeHtml(Path.GetFileName(screenshot)));
                sb.AppendLine();
                sb.AppendLine("</div>");
            }
            sb.AppendLine("</div>");
        }

        sb.AppendLine("</div>");
        sb.AppendLine("</div>");
    }

    private static void AppendFrameMetricRow(StringBuilder sb, string name, double value, string unit, double? warningThreshold, double? errorThreshold, bool? higherIsWorse)
    {
        var (status, cssClass) = GetThresholdStatus(value, warningThreshold, errorThreshold, higherIsWorse ?? false);
        sb.AppendLine("<tr>");
        sb.AppendFormat("<td>{0}</td>", EscapeHtml(name));
        sb.AppendLine();
        sb.AppendFormat("<td class=\"{0}\">{1} {2}</td>", cssClass, value.ToString("F2", CultureInfo.InvariantCulture), EscapeHtml(unit));
        sb.AppendLine();
        if (warningThreshold.HasValue && errorThreshold.HasValue)
            sb.AppendFormat("<td>Warn: {0} / Error: {1}</td>", warningThreshold.Value.ToString(CultureInfo.InvariantCulture), errorThreshold.Value.ToString(CultureInfo.InvariantCulture));
        else
            sb.AppendLine("<td>-</td>");
        sb.AppendLine();
        sb.AppendFormat("<td class=\"{0}\">{1}</td>", cssClass, status);
        sb.AppendLine();
        sb.AppendLine("</tr>");
    }

    private static void AppendFrameMetricRow(StringBuilder sb, string name, long value, string unit, long? warningThreshold, long? errorThreshold, bool? higherIsWorse)
    {
        var (status, cssClass) = GetThresholdStatus(value, warningThreshold, errorThreshold, higherIsWorse ?? false);
        sb.AppendLine("<tr>");
        sb.AppendFormat("<td>{0}</td>", EscapeHtml(name));
        sb.AppendLine();
        sb.AppendFormat("<td class=\"{0}\">{1} {2}</td>", cssClass, value.ToString(CultureInfo.InvariantCulture), EscapeHtml(unit));
        sb.AppendLine();
        if (warningThreshold.HasValue && errorThreshold.HasValue)
            sb.AppendFormat("<td>Warn: {0} / Error: {1}</td>", warningThreshold.Value.ToString(CultureInfo.InvariantCulture), errorThreshold.Value.ToString(CultureInfo.InvariantCulture));
        else
            sb.AppendLine("<td>-</td>");
        sb.AppendLine();
        sb.AppendFormat("<td class=\"{0}\">{1}</td>", cssClass, status);
        sb.AppendLine();
        sb.AppendLine("</tr>");
    }

    private static void AppendDiagnostics(StringBuilder sb, IReadOnlyList<Diagnostic> diagnostics)
    {
        if (diagnostics.Count == 0) return;

        sb.AppendLine("<div class=\"card\">");
        sb.AppendLine("<h2>Diagnostics</h2>");
        sb.AppendLine("<ul class=\"diag-list\">");

        foreach (var diag in diagnostics.OrderByDescending(d => d.Severity))
        {
            var cssClass = diag.Severity == DiagnosticSeverity.Error ? "diag-error" : "diag-warn";
            var location = diag.LineNumber.HasValue
                ? $"{Path.GetFileName(diag.Path)}:{diag.LineNumber.Value}"
                : Path.GetFileName(diag.Path);

            sb.AppendFormat("<li class=\"diag-item {0}\">", cssClass);
            sb.AppendLine();
            sb.AppendFormat("<span class=\"diag-code\">{0}</span>", EscapeHtml(diag.Code));
            sb.AppendFormat("<span class=\"diag-msg\">{0}", EscapeHtml(diag.Message));
            if (!string.IsNullOrWhiteSpace(diag.SuggestedFix))
                sb.AppendFormat(" <em>({0})</em>", EscapeHtml(diag.SuggestedFix));
            sb.AppendLine("</span>");
            sb.AppendFormat("<span class=\"diag-location\">{0}</span>", EscapeHtml(location));
            sb.AppendLine();
            sb.AppendLine("</li>");
        }

        sb.AppendLine("</ul>");
        sb.AppendLine("</div>");
    }

    private static string GetRelativePath(string baseDir, string targetPath)
    {
        var baseUri = new Uri(baseDir.EndsWith(Path.DirectorySeparatorChar.ToString()) ? baseDir : baseDir + Path.DirectorySeparatorChar);
        var targetUri = new Uri(targetPath);
        return Uri.UnescapeDataString(baseUri.MakeRelativeUri(targetUri).ToString().Replace('/', Path.DirectorySeparatorChar));
    }

    private static string EscapeHtml(string? value)
    {
        if (value is null) return string.Empty;
        return System.Net.WebUtility.HtmlEncode(value);
    }
}
