<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UnrealKit.Core\UnrealKit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Scriban" Version="7.4.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Support\HtmlTableReport.sbnhtml" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
