<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>UnrealKit.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.7" />
    <PackageReference Include="CUE4Parse" Version="1.2.2.202609" />
    <PackageReference Include="CUE4Parse-Conversion" Version="1.2.2.202609" />
    <PackageReference Include="FluentFTP" Version="54.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="BaseGame.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>